name: Build Kernel with default

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ccache zip

      - name: Restore ccache Cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/ccache
          key: ${{ runner.os }}-ccache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Set up Environment Variables
        run: |
          echo "BUILD_START=$(date +%s)" >> $GITHUB_ENV
          echo "TCDIR=${HOME}/android/TOOLS/GCC" >> $GITHUB_ENV

      - name: Prepare Directories
        run: |
          [ -d "out" ] && rm -rf out
          mkdir -p out
          mkdir -p $TCDIR

      - name: Download ARM64 Toolchain
        run: |
          if [ ! -d "$TCDIR/los-4.9-64" ]; then
            echo "ARM64 TC Not Present. Downloading..."
            git clone --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9 $TCDIR/los-4.9-64
          else
            echo "ARM64 TC Present."
          fi

      - name: Download ARM32 Toolchain
        run: |
          if [ ! -d "$TCDIR/los-4.9-32" ]; then
            echo "ARM32 TC Not Present. Downloading..."
            git clone --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9 $TCDIR/los-4.9-32
          else
            echo "ARM32 TC Present."
          fi

      - name: Run Kernel Build
        run: |
          make O=out ARCH=arm64 a37f_defconfig
          PATH="$TCDIR/los-4.9-64/bin:$TCDIR/los-4.9-32/bin:$PATH" \
          make O=out ARCH=arm64 \
              CC="ccache $TCDIR/los-4.9-64/bin/aarch64-linux-android-gcc" \
              CROSS_COMPILE=aarch64-linux-android- \
              CROSS_COMPILE_ARM32=arm-linux-androideabi- \
              CONFIG_NO_ERROR_ON_MISMATCH=y \
              CONFIG_DEBUG_SECTION_MISMATCH=y \
              -j$(nproc --all)

      - name: Package Kernel
        run: |
          cp out/arch/arm64/boot/Image anykernel3
          gcc anykernel3/dtbtool.c -o out/arch/arm64/boot/dts/dtbtool
          (cd out/arch/arm64/boot/dts && ./dtbtool -v -s 2048 -o dt.img)
          cp out/arch/arm64/boot/dts/dt.img anykernel3
          (cd anykernel3 && zip -r ../out/A37F_KERNEL_$(date +%d.%m.%Y_%H:%M:%S).zip . -x 'LICENSE' 'README.md' 'dtbtool.c')

      - name: Save ccache Cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/ccache
          key: ${{ runner.os }}-ccache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: kernel-build
          path: out/*.zip

      - name: Display Build Time
        run: |
          BUILD_END=$(date +%s)
          DIFF=$((BUILD_END - $BUILD_START))
          echo -e "\e[1;42mBuild completed in $((DIFF / 60)) minute(s) and $((DIFF % 60)) seconds.\e[0m"
